from linkedin_web_scraper._compat import warn_legacy_namespace
from linkedin_web_scraper.config.job_scraper_advanced_config import JobScraperAdvancedConfig

warn_legacy_namespace("LinkedInWebScraper.job_scraper_advanced_config")

__all__ = ["JobScraperAdvancedConfig"]