from __future__ import annotations

TECH_STACK_CATEGORIES = {
    "Agile Methodologies": ["Scrum", "SAFe", "Agile", "Agile SDLC", "Kanban", "Agile"],
    "Back-End Development": [
        "Node.js",
        "ASP.NET",
        "Spring Boot",
        "Django",
        "Flask",
        "Ruby on Rails",
        ".NET Core",
        "FastAPI",
        "Golang",
        "C#",
    ],
    "Big Data Tools": [
        "Hadoop",
        "Spark",
        "Hive",
        "Databricks",
        "Airflow",
        "BigQuery",
        "Teradata",
        "ClickHouse",
        "AWS Glue",
        "Big Data",
        "Big Data Stack",
        "SnapLogic",
        "DataDog",
        "Alteryx",
        "Talend ETL",
    ],
    "Cloud Platforms": [
        "AWS",
        "Azure",
        "GCP",
        "Google Cloud Platform (GCP)",
        "Cloud Computing",
        "Microsoft Azure",
        "AWS Redshift",
        "AWS S3",
        "Azure SQL Databases",
        "Google BigQuery",
        "Azure Data Factory",
        "Azure Synapse",
        "Azure API App Services",
        "Azure Data Bricks",
        "Azure Data Lake",
        "Azure ADLS Gen2",
        "AWS Lambda",
        "Google Cloud",
        "Azure Data Lake Storage",
        "Amazon Web Services",
        "Cloud Infrastructure",
    ],
    "Containerization and Orchestration": [
        "Docker",
        "Kubernetes",
        "Containerization",
        "ECS",
        "LXD",
    ],
    "Data Analysis": [
        "Data Analysis",
        "Statistical Modeling",
        "Statistical Analysis",
        "Data Analytics",
        "Data Mining",
        "Data Quality",
        "Data Cleansing",
        "Data Normalization",
        "Data Sanitization",
        "Statistical Techniques",
        "Statistical Methods",
        "Analytical Tools",
        "Data Management",
        "Data Science",
        "Data Science Tools",
        "Data Modeling",
        "Data Queries",
        "Data Flows",
        "Data Manipulation",
        "Data Platforms",
        "Data Warehousing",
        "Data Engineering",
        "Data Visualization",
        "Data Visualization Tools",
    ],
    "Data Engineering": [
        "Data Engineering",
        "Data Warehousing",
        "ETL",
        "Data Lakes",
        "Data Flows",
        "Data Migrations",
        "Data Integration",
        "Data Processing",
        "Data Platforms",
        "Data Quality",
        "Data Management",
    ],
    "Data Modeling": [
        "Data Modeling",
        "Data Architectures",
        "Data Structures",
        "Data Schema Design",
        "Database Modeling",
        "Conceptual Data Models",
        "Logical Data Models",
        "Physical Data Models",
    ],
    "Data Visualization": [
        "Power BI",
        "Tableau",
        "Qlik",
        "Matplotlib",
        "Plotly",
        "D3.js",
        "Excel",
        "Looker",
        "Apache Superset",
        "Data Visualization Tools",
        "BI Tools",
        "Dashboard Development",
        "Visualization Tools",
    ],
    "Database Management": [
        "SQL",
        "NoSQL",
        "MongoDB",
        "SQL Server",
        "CosmosDB",
        "MySQL",
        "PostgreSQL",
        "Oracle",
        "SAP HANA",
        "SAP ECC",
        "SAP S/4HANA",
        "Non-SQL Databases",
        "DB2",
        "PL/SQL",
        "Cassandra",
        "Redis",
        "Sybase",
        "Data Lake",
        "Database",
        "Database Management",
        "Data Warehouses",
        "Database Schema Design",
        "Stored Procedures",
        "Data Migrations",
        "SQL DW",
        "PostgresSQL",
    ],
    "Front-End Development": [
        "React",
        "Angular",
        "Bootstrap",
        "Vue.js",
        "CSS",
        "HTML",
        "SwiftUI",
        "Front End Development",
    ],
    "Infrastructure as Code (IaC) and Automation": [
        "Terraform",
        "Ansible",
        "Helm",
        "OpenStack",
        "Infrastructure-as-Code",
        "ARM Templates",
        "Automation",
        "Git",
        "CI/CD pipelines",
    ],
    "Machine Learning": [
        "Scikit-Learn",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "MLFlow",
        "Spark ML",
        "XGBoost",
        "LightGBM",
        "Feature Engineering",
        "A/B Testing",
        "Machine Learning",
        "Algorithms",
        "Google AutoML",
        "Hugging Face",
        "Kubeflow",
        "SciPy",
        "ML Models",
    ],
    "Networking": ["WiFi", "Networking", "VPC", "Network Security", "Cloud Security"],
    "Python": ["Python"],
    "Testing and Quality Assurance": [
        "Unit Testing",
        "Integration Testing",
        "Feature Testing",
        "Performance Tuning",
        "Load Testing",
        "Testing Tools",
        "SOAP UI",
        "Quality Assurance",
    ],
}
